In [29]:
import tensorflow as tf 
import numpy as np

In [38]:
tf.reset_default_graph()
def convolution(input_img):
    conv_in = tf.placeholder(
        dtype = tf.float32,
        shape = [1, 5, 5, 1],
        name = "conv_in"
    )
    conv_out = tf.layers.conv2d(
        inputs = conv_in,
        filters = 1,
        kernel_size = [3,3],
        padding = "valid"
    )
    config = tf.ConfigProto()
    config.gpu_options.allow_growth=True
    sess = tf.Session(config=config)
    sess.run(tf.global_variables_initializer())
    return sess.run(conv_out, feed_dict =
                    {conv_in: input_img})

In [39]:
input_img = np.array([[[[1],[1],[1],[1],[1]],
                       [[1],[1],[1],[1],[1]],
                       [[1],[1],[1],[1],[1]],
                       [[1],[1],[1],[1],[1]],
                       [[1],[1],[1],[1],[1]]]])
print(convolution(input_img))

[[[[ 0.9154582]
   [ 0.9154582]
   [ 0.9154582]]

  [[ 0.9154582]
   [ 0.9154582]
   [ 0.9154582]]

  [[ 0.9154582]
   [ 0.9154582]
   [ 0.9154582]]]]


In [53]:
tf.reset_default_graph()
def deconv(input_img):
    deconv_in = tf.placeholder(
        dtype = tf.float32,
        shape = [1, None, None,1],
        name = "deconv_in"
    )
    deconv_out = tf.layers.conv2d_transpose(
        inputs = deconv_in,
        filters = 1,
        kernel_size = [3,3],
        padding = "valid",
        strides = 2
    )
    config = tf.ConfigProto()
    config.gpu_options.allow_growth=True
    sess = tf.Session(config=config)
    sess.run(tf.global_variables_initializer())
    return sess.run(deconv_out, feed_dict =
                    {deconv_in: input_img})

In [54]:
input_img = np.array([[[[1],[1],[1],[1],[1]],
                       [[1],[1],[1],[1],[1]],
                       [[1],[1],[1],[1],[1]],
                       [[1],[1],[1],[1],[1]],
                       [[1],[1],[1],[1],[1]]]])
print(deconv(input_img))

[[[[-0.05527031]
   [ 0.22204792]
   [ 0.42342889]
   [ 0.22204792]
   [ 0.42342889]
   [ 0.22204792]
   [ 0.42342889]
   [ 0.22204792]
   [ 0.42342889]
   [ 0.22204792]
   [ 0.47869921]]

  [[ 0.36087394]
   [-0.1582121 ]
   [-0.10632509]
   [-0.1582121 ]
   [-0.10632509]
   [-0.1582121 ]
   [-0.10632509]
   [-0.1582121 ]
   [-0.10632509]
   [-0.1582121 ]
   [-0.46719903]]

  [[ 0.08274949]
   [ 0.20116836]
   [ 0.01866841]
   [ 0.20116836]
   [ 0.01866841]
   [ 0.20116836]
   [ 0.01866841]
   [ 0.20116836]
   [ 0.01866841]
   [ 0.20116836]
   [-0.06408107]]

  [[ 0.36087394]
   [-0.1582121 ]
   [-0.10632509]
   [-0.1582121 ]
   [-0.10632509]
   [-0.1582121 ]
   [-0.10632509]
   [-0.1582121 ]
   [-0.10632509]
   [-0.1582121 ]
   [-0.46719903]]

  [[ 0.08274949]
   [ 0.20116836]
   [ 0.01866841]
   [ 0.20116836]
   [ 0.01866841]
   [ 0.20116836]
   [ 0.01866841]
   [ 0.20116836]
   [ 0.01866841]
   [ 0.20116836]
   [-0.06408107]]

  [[ 0.36087394]
   [-0.1582121 ]
   [-0.10632509]
   [